FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY README.md ./README.md
COPY cmd ./cmd
COPY internal ./internal
COPY pkg ./pkg
COPY resources ./resources

RUN mkdir temp

RUN go test -v ./...

RUN CGO_ENABLED=0 GOOS=linux go build -o pvault cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/pvault .

ENTRYPOINT [ "./pvault" ]
