name: Publish docker image

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    tag_repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Extract version from cmd/sub/version.go
              id: get_version
              run: |
                  TAG_NAME=v$(grep "const Version =" cmd/sub/version.go | grep "const Version =" | sed -e 's-.*= "--' -e 's-".*--')
                  echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
            - name: Create a tag
              env:
                  TAG_NAME: ${{ env.tag_name }}
              uses: actions/github-script@v5
              with:
                  script: |
                      github.rest.git.createRef({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      ref: `refs/tags/${process.env.TAG_NAME}`,
                      sha: context.sha
                      })
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.TAG_NAME }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    docker-build:
        name: Build docker
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build Image
              run: make build-docker
            - name: Publish Image
              run: make docker-publish
