name: draw tests

on:
  pull_request:
    branches: [main]

jobs:
  test_on_pr:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Test with the Go CLI
        run: go test ./...